// <auto-generated />
using System;
using Financial.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Financial.Migrations
{
    [DbContext(typeof(FinancialContext))]
    [Migration("20200604210934_SetCalendarStringLength")]
    partial class SetCalendarStringLength
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Financial.Models.Entities.Account", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("Credit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserGuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Guid");

                    b.HasIndex("UserGuid");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Financial.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NationalCode")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "1e8b24df-cf91-4a8a-a3dd-89c37b8ee4f9",
                            AccessFailedCount = 0,
                            Address = "تهران - لواسان",
                            ConcurrencyStamp = "3485e6d6-6bb4-49ea-a522-8f810f10b9b5",
                            CreationDate = new DateTime(2020, 6, 5, 1, 39, 34, 97, DateTimeKind.Local).AddTicks(5013),
                            EmailConfirmed = false,
                            FirstName = "سید مهدی",
                            IsDelete = false,
                            LastName = "رودکی",
                            LockoutEnabled = true,
                            ModifiedDate = new DateTime(2020, 6, 5, 1, 39, 34, 97, DateTimeKind.Local).AddTicks(5013),
                            NationalCode = "0440675014",
                            NormalizedUserName = "H4N60V3R",
                            PasswordHash = "AQAAAAEAACcQAAAAEPYzk6lUm9l1Iq+mwvjUx7DtRDKN2uEw6bFp4ZJ+d4KfPH+APxsjZa4W8ln0rQlgPQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "645UFGOLF7LIMLIQ6TVG7IUJ2SJ62CWM",
                            TwoFactorEnabled = false,
                            UserName = "h4n60v3r"
                        });
                });

            modelBuilder.Entity("Financial.Models.Entities.Calendar", b =>
                {
                    b.Property<int>("CalendarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CalendarID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("CalendarGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CalendarGUID")
                        .HasColumnType("UNIQUEIDENTIFIER ROWGUIDCOL")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("End")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Start")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CalendarId");

                    b.ToTable("Calendar");
                });

            modelBuilder.Entity("Financial.Models.Entities.CheckTransactionInfo", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("IssueDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<Guid>("TransactionGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Guid")
                        .HasName("PK_CheckTransactionInfo");

                    b.HasIndex("TransactionGuid");

                    b.ToTable("CheckTransactionInfo");
                });

            modelBuilder.Entity("Financial.Models.Entities.Code", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("CodeGroupGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DisplayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("Guid");

                    b.HasIndex("CodeGroupGuid");

                    b.ToTable("Code");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("d1605abf-8a46-4f2e-8e22-194298b9fd33"),
                            CodeGroupGuid = new Guid("8d9375da-33d4-41f0-b589-d91c96af8eb5"),
                            CreationDate = new DateTime(2020, 6, 5, 1, 39, 34, 97, DateTimeKind.Local).AddTicks(5013),
                            DisplayValue = "دریافتی",
                            IsDelete = false,
                            ModifiedDate = new DateTime(2020, 6, 5, 1, 39, 34, 97, DateTimeKind.Local).AddTicks(5013),
                            Value = "Creditor"
                        },
                        new
                        {
                            Guid = new Guid("749d242b-55f7-4361-bf1b-42c139411c49"),
                            CodeGroupGuid = new Guid("8d9375da-33d4-41f0-b589-d91c96af8eb5"),
                            CreationDate = new DateTime(2020, 6, 5, 1, 39, 34, 97, DateTimeKind.Local).AddTicks(5013),
                            DisplayValue = "پرداختی",
                            IsDelete = false,
                            ModifiedDate = new DateTime(2020, 6, 5, 1, 39, 34, 97, DateTimeKind.Local).AddTicks(5013),
                            Value = "Debtor"
                        },
                        new
                        {
                            Guid = new Guid("b508bd08-5534-4d26-9ed4-c36575c8d90a"),
                            CodeGroupGuid = new Guid("b7a903f3-2c65-49ef-997b-03966578a4c0"),
                            CreationDate = new DateTime(2020, 6, 5, 1, 39, 34, 97, DateTimeKind.Local).AddTicks(5013),
                            DisplayValue = "وصول شده",
                            IsDelete = false,
                            ModifiedDate = new DateTime(2020, 6, 5, 1, 39, 34, 97, DateTimeKind.Local).AddTicks(5013),
                            Value = "Passed"
                        },
                        new
                        {
                            Guid = new Guid("3d905312-ae57-498c-a733-f5cbaf114940"),
                            CodeGroupGuid = new Guid("b7a903f3-2c65-49ef-997b-03966578a4c0"),
                            CreationDate = new DateTime(2020, 6, 5, 1, 39, 34, 97, DateTimeKind.Local).AddTicks(5013),
                            DisplayValue = "وصول نشده",
                            IsDelete = false,
                            ModifiedDate = new DateTime(2020, 6, 5, 1, 39, 34, 97, DateTimeKind.Local).AddTicks(5013),
                            Value = "NotPassed"
                        },
                        new
                        {
                            Guid = new Guid("fe92b8f8-f206-4273-8ca8-f1ecf70a8197"),
                            CodeGroupGuid = new Guid("b7a903f3-2c65-49ef-997b-03966578a4c0"),
                            CreationDate = new DateTime(2020, 6, 5, 1, 39, 34, 97, DateTimeKind.Local).AddTicks(5013),
                            DisplayValue = "در انتظار وصول",
                            IsDelete = false,
                            ModifiedDate = new DateTime(2020, 6, 5, 1, 39, 34, 97, DateTimeKind.Local).AddTicks(5013),
                            Value = "Waiting"
                        });
                });

            modelBuilder.Entity("Financial.Models.Entities.CodeGroup", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Guid");

                    b.ToTable("CodeGroup");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("b7a903f3-2c65-49ef-997b-03966578a4c0"),
                            CreationDate = new DateTime(2020, 6, 5, 1, 39, 34, 97, DateTimeKind.Local).AddTicks(5013),
                            IsDelete = false,
                            Key = "TransactionState",
                            ModifiedDate = new DateTime(2020, 6, 5, 1, 39, 34, 97, DateTimeKind.Local).AddTicks(5013)
                        },
                        new
                        {
                            Guid = new Guid("8d9375da-33d4-41f0-b589-d91c96af8eb5"),
                            CreationDate = new DateTime(2020, 6, 5, 1, 39, 34, 97, DateTimeKind.Local).AddTicks(5013),
                            IsDelete = false,
                            Key = "TransactionType",
                            ModifiedDate = new DateTime(2020, 6, 5, 1, 39, 34, 97, DateTimeKind.Local).AddTicks(5013)
                        });
                });

            modelBuilder.Entity("Financial.Models.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("AccountGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountSide")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<long>("Cost")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StateCodeGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<Guid>("TypeCodeGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Guid")
                        .HasName("PK_Transaction");

                    b.HasIndex("AccountGuid");

                    b.HasIndex("StateCodeGuid");

                    b.HasIndex("TypeCodeGuid");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Financial.Models.Entities.Account", b =>
                {
                    b.HasOne("Financial.Models.Entities.ApplicationUser", "User")
                        .WithMany("Account")
                        .HasForeignKey("UserGuid")
                        .HasConstraintName("FK_Account_User")
                        .IsRequired();
                });

            modelBuilder.Entity("Financial.Models.Entities.CheckTransactionInfo", b =>
                {
                    b.HasOne("Financial.Models.Entities.Transaction", "Transaction")
                        .WithMany("CheckTransactionInfo")
                        .HasForeignKey("TransactionGuid")
                        .HasConstraintName("FK_CheckTransactionInfo_Transaction")
                        .IsRequired();
                });

            modelBuilder.Entity("Financial.Models.Entities.Code", b =>
                {
                    b.HasOne("Financial.Models.Entities.CodeGroup", "CodeGroup")
                        .WithMany("Code")
                        .HasForeignKey("CodeGroupGuid")
                        .HasConstraintName("FK_Code_CodeGroup")
                        .IsRequired();
                });

            modelBuilder.Entity("Financial.Models.Entities.Transaction", b =>
                {
                    b.HasOne("Financial.Models.Entities.Account", "Account")
                        .WithMany("Transaction")
                        .HasForeignKey("AccountGuid")
                        .HasConstraintName("FK_Transaction_Account");

                    b.HasOne("Financial.Models.Entities.Code", "StateCode")
                        .WithMany("StateTransaction")
                        .HasForeignKey("StateCodeGuid")
                        .HasConstraintName("FK_StateTransaction_StateCode")
                        .IsRequired();

                    b.HasOne("Financial.Models.Entities.Code", "TypeCode")
                        .WithMany("TypeTransaction")
                        .HasForeignKey("TypeCodeGuid")
                        .HasConstraintName("FK_TypeTransaction_TypeCode")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Financial.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Financial.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Financial.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Financial.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
